### ISSUE TITLE
HelperScripts/AllGradesTable.R missing

### ISSUE THREAD

**Issue by ryanlovett** [shinyscope/shinyscope#23]
When running the latest version, shiny errors with:
```
Warning: Navigation containers expect a collection of `bslib::nav()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
Warning in file(filename, "r", encoding = encoding) :
  cannot open file 'HelperScripts/AllGradesTable.R': No such file or directory
Warning: Error in file: cannot open the connection
  51: file
  50: source
   1: runApp
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
```

**Comment by mvoutov** [comment]
@ryanlovett is this still the case? My latest commit made changes to this file. Not sure if it will fix the issue?

**Comment by ryanlovett** [comment]
@mvoutov Yes, the issue is still present. In the github repo there is a file named `AllGradestable.R` and not `AllGradesTable.R`. Note the capital `T`. Some filesystems, like on macOS, are case-preserving, but not case-aware. So they use whatever case you provide, but don't disambiguate when characters match even if their case doesn't. This means that even if the code and actual filename differ (as they do now), it will still work on macOS. It will not work on most other operating system filesystems however.

**Comment by mvoutov** [comment]
@ryanlovett Oh, now I got it! Okay, I changed the name to GradesTable.R because it did not recognize the change of case as a change actually to commit.

**Comment by ryanlovett** [comment]
@mvoutov Looks good. I can confirm that the app now works properly for me on Linux. Thanks!

**Comment by ryanlovett** [comment]
Apparently you can also run `git config core.ignorecase false` so that git pays attention to case.
