### ISSUE TITLE
Publish on DataHub

### ISSUE THREAD

**Issue by andrewpbray** [shinyscope/shinyscope#8]
- [x] Figure out how to deploy to shiny.datahub.berkeley.edu using nbgitpuller
- [x] Figure out how to have persistent local file storage on DataHub

**Comment by ryanlovett** [comment]
You can click on the following link to pull using nbgitpuller:

https://shiny.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fshinyscope%2Fshinyscope&urlpath=shiny%2Fshinyscope%2F&branch=master

The link was built from nbgitpuller.link which is a link to https://nbgitpuller.readthedocs.io/en/latest/link.html. I entered the shiny hub url, git repo, and clicked the Shiny radio button.

To debug shiny app failures, you can replace `shiny` in the URL with `rstudio`, e.g. https://shiny.datahub.berkeley.edu/user/rylo/rstudio/. Then you can run the app by navigating to `shinyscope/R/`, open `app.R`, and run the app.
<img width="1198" alt="Screenshot 2023-04-10 at 11 26 00 AM" src="https://user-images.githubusercontent.com/10248125/230967471-f32c3281-eadc-4f6c-8d67-dcb3612a5f55.png">

At the moment, there's an issue with a missing file in `helperScripts/` which I can make an issue about.

**Comment by ryanlovett** [comment]
Created https://github.com/shinyscope/shinyscope/pull/9 which fixes a problem on case-sensitive filesytems (which are used in most places, including shiny.datahub).

**Comment by andrewpbray** [comment]
Heyo!

Your link totally works for me - that's great.  I tried to modify it to open up the R directory (which I have to do to manually to move from the jupyterhub directory into the actual app), but the link isn't generating. Is there anything I'm missing?

<img width="1281" alt="Screen Shot 2023-04-10 at 12 17 57 PM" src="https://user-images.githubusercontent.com/1627362/230979469-eaa01910-781c-456b-a0fd-91e25d4c6049.png">

**Comment by ryanlovett** [comment]
This should be the full nbgitpuller link:

https://shiny.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fshinyscope%2Fshinyscope&urlpath=shiny%2Fshinyscope%2FR%2F

The url path would be `shiny/shinyscope/R/`, with no file.

**Comment by andrewpbray** [comment]
@ryanlovett Awesome!

Ok, next question when you have a moment: file storage on datahub.

The primary user workflow we're imagining right now is that users would click the link to get into their authenticated session with the most recent (or a specifc) version of the app from github. When they get there the first time, they'd upload the gradescope csv from their local machine (or maybe sync with gradescope if we can figure out the api).

It'd be very handy if, once uploaded, that file would be persistent across sessions. However, this article in the shiny docs suggest we can't store data inside the app itself.

[https://shiny.rstudio.com/articles/share-data.html](https://shiny.rstudio.com/articles/share-data.html
)

However this post makes it sound possible, i.e. that shiny server doesn't prevent you from writing to the machine running the app as long as you have requisite permissions:

<https://daattali.com/shiny/persistent-data-storage/>

I don't really know how these apps are run on top of a datahub machine, but does that setup allow us to get around this?

**Comment by ryanlovett** [comment]
@andrewpbray The first doc describes file storage for the hosted shinyapps.io service, but not shiny itself. If shinyscope uses standard posix calls to save files and if shiny doesn't explicitly inhibit file writes, it should have no trouble saving them to the home directory of the user on shiny.datahub. Anything under /home/rstudio persists across session restarts.

I would say that the app should not write data to the working directory of the repo that gets pulled. You can make a ~/shinyscope-data or ~/.local/shinyscope/ or some such for longer term storage.

**Comment by andrewpbray** [comment]
Makes sense.

I just put an event on your calendar for tomorrow afternoon 3-4 to chat about this (feel free to decline if you've got other stuff to work on this week). Just so that I have it on hand, here's a package that might be helpful in managing the UI for such a file system: <https://github.com/thomasp85/shinyFiles>
